In [2]:
#Importing the required library for latin hypersquare sampling
from scipy.stats import qmc
import pandas as pd
import csv

In [5]:
#Define the variables and acceptable ranges [cac03_flow_rate, calciner_temp, pellet_moisture_frac, air_mol_flow_rate, RH_air, DAC_column_height, pellet_diameter, DAC_ambient_temp]
lhs_variables =  {
    "caco3_flow_rate [kmol/hr]": [5, 100],                       # in kmol/hr
    "calciner_temp [Deg C]": [890, 950],                            #calciner temp without too much sintering (in degree c)
    "pellet_moisture_frac": [0.05, 0.5],                            # a decimal number
    "air_mol_flow_rate [kmol/hr]": [7000, 9000],                    # in kmol/hr
    "RH_air": [0.1, 0.9],                                           # relative humidity, less than 1
    "DAC_column_height [m]": [1.0, 10.0],                            # height in meters
    "pellet_diameter [mm]": [1.0, 6.0],                             # in mm
    "DAC_ambient_temp [Deg C]": [15, 45],                           # in degree celsius
    "e_voidage": [0.35, 0.45]                                         #Voidage in the DAC unit
}


#Set your dimensions d and initiate sampler
sampler = qmc.LatinHypercube(d=len(lhs_variables), seed=42)

#Next, set the number of samples preferred
sample = sampler.random(n=1100)

#scale samples to specific ranges, important as industrial processes have real constraints. format [min, max]. 
#[cac03_flow_rate, calciner_temp, pellet_moisture_frac, air_flow_rate, RH_air, DAC_column_height, pellet_diameter, DAC_temp]
#define the lower and upper bounds
l_bounds = [r[0] for r in lhs_variables.values()]
u_bounds = [r[1] for r in lhs_variables.values()]

#generate and print scaled sample

scaled_sample = qmc.scale(sample, l_bounds, u_bounds)

#convert to data frame
df_lhs = pd.DataFrame(scaled_sample, columns=lhs_variables.keys())
index = [i for i in range(0, len(df_lhs))]
df_lhs["sim_index"] = index

#export to csv
df_lhs.to_csv("LHS_variables_to_be_manipulated_by_python.csv", index=False, encoding="utf-8")

In [6]:
#read in dataframe
#df = pd.read_csv("LHS_variables_to_be_manipulated_by_python.csv")

#print first 5 columns
df_lhs.head()

,caco3_flow_rate [kmol/hr],calciner_temp [Deg C],pellet_moisture_frac,air_mol_flow_rate [kmol/hr],RH_air,DAC_column_height [m],pellet_diameter [mm],DAC_ambient_temp [Deg C],e_voidage,sim_index
0,97.514977,921.285152,0.493512,8833.277513,0.801022,4.919290,3.805631,21.742198,0.439079,0
1,31.906558,939.507047,0.333939,8082.465700,0.767765,2.624554,5.462603,34.839420,0.427176,1
2,66.419432,929.838273,0.426463,7335.719044,0.836021,1.900874,4.928280,24.921964,0.429412,2
3,5.255308,916.227948,0.082039,8304.100432,0.103660,9.760061,4.125589,21.887194,0.418892,3
4,99.038780,900.174052,0.347316,7315.145793,0.575318,9.355005,4.346817,38.664208,0.397470,4

In [9]:
df = pd.read_csv("LHS_variables_to_be_manipulated_by_python.csv")

In [10]:
df

,caco3_flow_rate [kmol/hr],calciner_temp [Deg C],pellet_moisture_frac,air_mol_flow_rate [kmol/hr],RH_air,DAC_column_height [m],pellet_diameter [mm],DAC_ambient_temp [Deg C],e_voidage,sim_index
0,97.514977,921.285152,0.493512,8833.277513,0.801022,4.919290,3.805631,21.742198,0.439079,0
1,31.906558,939.507047,0.333939,8082.465700,0.767765,2.624554,5.462603,34.839420,0.427176,1
2,66.419432,929.838273,0.426463,7335.719044,0.836021,1.900874,4.928280,24.921964,0.429412,2
3,5.255308,916.227948,0.082039,8304.100432,0.103660,9.760061,4.125589,21.887194,0.418892,3
4,99.038780,900.174052,0.347316,7315.145793,0.575318,9.355005,4.346817,38.664208,0.397470,4
...,...,...,...,...,...,...,...,...,...,...
1095,50.419064,931.582229,0.154068,7646.329962,0.871272,2.471474,2.465906,36.134729,0.415279,1095
1096,20.367716,905.685989,0.261500,7404.025181,0.680243,8.748796,2.436164,15.250342,0.353304,1096
1097,13.269341,943.607141,0.311672,8443.948358,0.492100,5.956748,2.016575,34.602614,0.440534,1097
1098,24.203261,930.235680,0.242999,8127.516368,0.417274,5.403669,4.581640,40.993224,0.449766,1098
1099,41.747399,915.090332,0.400224,7659.011108,0.364127,6.059182,2.760015,29.408375,0.417007,1099